version: '3.9'

services:
  viral-nation-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: viral-nation
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=4000
    depends_on:
      - redis
      - postgres
    links:
      - "postgres"
    volumes:
      - ./mount/src:/app/src
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
